image: node:alpine

stages:
  - test

Prepare:
  stage: test
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - yarn
  script:
    - yarn prepare-env-dev

Run:
  stage: test
  only:
    - schedules
  script:
    - yarn test