image: node:16.14.2-alpine

stages:
  - prep
  - test

env-prep:
  stage: prep
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
  script:
    - yarn prepare-env-dev
  artifacts:
    paths:
    - .env
    expire_in: 12 hour

test:
  stage: test
  only:
    - schedules
  script:
    - yarn install
    - if [[ $TEST_STAKING == "true" ]] ;
      then
        yarn test src/staking ;
      fi
    - if [[ $TEST_VESTING == "true" ]] ;
      then
        yarn test src/vesting ;
      fi
    - if [[ $TEST_GOV == "true" ]] ;
      then
        yarn test src/gov ;
      fi
    - if [[ $TEST_TRANSFERS == "true" ]] ;
      then
        yarn test src/transfers ;
      fi
    - if [[ $TEST_ORACLE == "true" ]] ;
      then
        yarn test src/oracle ;
      fi

