image: node:16.14.2-alpine

stages:
  - prep
  - env
  - test

prep-node:
  stage: prep
  script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq

env-prep:
  stage: env
  only:
    - schedules
  script:
    - yarn prepare-env-dev
  artifacts:
    paths:
    - .env
    expire_in: 12 hour

test:
  stage: test
  only:
    - schedules
  script:
    - yarn install
    - /bin/bash ./scripts/run-tests-pipeline.sh

