image: node:16.14.2-alpine

stages:
  - prep
  - test

env-prep:
  stage: prep
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
    - yarn install
  script:
    - yarn prepare-env-dev

test:
  stage: test
  only:
    - schedules
  script:
    - yarn test
