stages:
  - prep
  - test

default:
  image: node:16.14.2-alpine

env-prep:
  variables:
    FEEDERS_FILE: "feeders.json"
    ACCOUNTS_DIR: "./accounts"
  stage: prep
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
  script:
    - yarn prepare-env-dev --mnemonic-faucet "$FAUCET_MNEMONIC_DEV"
        --mnemonic-contracts-owner "$SMART_CONTRACTS_ADMIN_MNEMONIC"
        --nolus-core-version-tag "$COSMZONE_PREFERRED_TAG"
        --test-transfer-flag "$TEST_TRANSFER_PIPELINE" --test-oracle-flag "$TEST_ORACLE_PIPELINE"
        --test-staking-flag "$TEST_STAKING_PIPELINE" --test-borrower-flag "$TEST_BORROWER_PIPELINE"
        --test-lender-flag "$TEST_LENDER_PIPELINE" --test-treasury-flag "$TEST_TREASURY_PIPELINE"
        --test-vesting-flag "$TEST_VESTING_PIPELINE" --test-gov-flag "$TEST_GOV_PIPELINE"
    - yarn save-feeders --accounts-dir "$ACCOUNTS_DIR" --feeders-file "$FEEDERS_FILE"
  artifacts:
    paths:
    - .env
    - $FEEDERS_FILE

test:
  stage: test
  only:
    - schedules
  before_script:
    - apk update && apk add bash
  script:
    - yarn install
    - yarn run test

