stages:
  - prep
  - test

default:
  image: node:16.14.2-alpine

env-prep:
  stage: prep
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
  script:
    - yarn prepare-env-dev --mnemonic-faucet "$FAUCET_MNEMONIC_DEV"
        --mnemonic-wasm-admin "$SMART_CONTRACTS_ADMIN_MNEMONIC"
        --token-type "JOB-TOKEN" --token-value "$CI_JOB_TOKEN" --tag "$COSMZONE_PREFERRED_TAG"
  artifacts:
    paths:
    - .env

test:
  stage: test
  only:
    - schedules
  before_script:
    - apk update && apk add bash
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - yarn install
    - yarn run-tests-pipeline

