stages:
  - test

default:
  image: node:16.14.2-alpine

env-prep:
  stage: test
  only:
    - schedules
  before_script:
    - apk update && apk add bash
    - apk --no-cache add curl
    - apk --no-cache add jq
  script:
    - yarn prepare-env-dev
  artifacts:
    paths:
    - .env
    expire_in: 12 hour

test:
  stage: test
  only:
    - schedules
  script:
    - yarn install
    - yarn run-tests-pipeline

