name: Test Suit
run-name: "Testing, triggered by ${{ github.actor }}"

on:
  # schedule:
  #   - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      nolus-preferred-tag:
        description: "Nolus-core preferred tag to use"
        type: string
      active-lease-address:
        description: "Lease with available interest"
        type: string
      test-transfer-pipeline:
        description: "Test transfer"
        type: boolean
      test-oracle-pipeline:
        description:  "Test oracle"
        type: boolean
      test-staking-pipeline:
        description:  "Test staking"
        type: boolean
      test-borrower-pipeline:
        description:  "Test borrower"
        type: boolean
      test-lender-pipeline:
        description:  "Test lender"
        type: boolean
      test-treasury-pipeline:
        description:  "Test treasury"
        type: boolean
      test-vesting-pipeline:
        description:  "Test vesting"
        type: boolean
      test-gov-pipeline:
        description:  "Test gov"
        type: boolean

jobs:
  env-prep:
    environment: dev
    env:
        ACCOUNTS_DIR: "./accounts"
        DEV_URL:  ${{ vars.DEV_URL }}
        FAUCET_MNEMONIC_DEV: ${{ secrets.FAUCET_MNEMONIC_DEV }}
        NOLUS_PREFERRED_TAG: ${{ github.event.inputs.nolus-preferred-tag || '' }}
        ACTIVE_LEASE_ADDRESS: ${{ github.event.inputs.active-lease-address || '' }}
        TEST_TRANSFER_PIPELINE: ${{ github.event.inputs.test-transfer-pipeline || 'true' }}
        TEST_ORACLE_PIPELINE: ${{ github.event.inputs.test-oracle-pipeline || 'true' }}
        TEST_STAKING_PIPELINE: ${{ github.event.inputs.test-staking-pipeline || 'true' }}
        TEST_BORROWER_PIPELINE: ${{ github.event.inputs.test-borrower-pipeline || 'true' }}
        TEST_LENDER_PIPELINE: ${{ github.event.inputs.test-lender-pipeline || 'true' }}
        TEST_TREASURY_PIPELINE: ${{ github.event.inputs.test-treasury-pipeline || 'true' }}
        TEST_VESTING_PIPELINE: ${{ github.event.inputs.test-vesting-pipeline || 'true' }}
        TEST_GOV_PIPELINE: ${{ github.event.inputs.test-gov-pipeline || 'true' }}
        TEST_PROFIT_PIPELINE: ${{ github.event.inputs.test-profit-pipeline || 'true' }}
        TEST_TIMEALARMS_PIPELINE: ${{ github.event.inputs.test-timealarms-pipeline || 'true' }}
        TEST_RESERVE_PIPELINE: ${{ github.event.inputs.test-reserve-pipeline || 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Install jq"
        run: sudo apt-get update && sudo apt-get install jq
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          yarn prepare-env-dev \
          --mnemonic-faucet "$FAUCET_MNEMONIC_DEV" \
          --nolus-core-version-tag "$NOLUS_PREFERRED_TAG" \
          --test-transfer-flag "$TEST_TRANSFER_PIPELINE" --test-oracle-flag "$TEST_ORACLE_PIPELINE" \
          --test-staking-flag "$TEST_STAKING_PIPELINE" --test-borrower-flag "$TEST_BORROWER_PIPELINE" \
          --test-lender-flag "$TEST_LENDER_PIPELINE" --test-treasury-flag "$TEST_TREASURY_PIPELINE" \
          --test-vesting-flag "$TEST_VESTING_PIPELINE" --test-gov-flag "$TEST_GOV_PIPELINE" --test-admin-flag "$TEST_ADMIN_PIPELINE" \
          --test-profit-flag "$TEST_PROFIT_PIPELINE" --test-timealarms-flag "$TEST_TIMEALARMS_PIPELINE" \
          --test-reserve-flag "$TEST_RESERVE_PIPELINE" --active-lease-address "$ACTIVE_LEASE_ADDRESS"
      - name: "Upload .env artifact"
        uses: actions/upload-artifact@v3
        with:
          name: .env
          path: .env

  test:
    runs-on: ubuntu-latest
    needs: env-prep
    steps:
      - uses: actions/checkout@v3
      - name: "Download the .env file"
        uses: actions/download-artifact@v3
        with:
          name: .env
      - uses: actions/setup-node@v3
      - run: yarn
      - run: yarn run test